import type { Project, Message, Task, QuickAction, Integration, AppNotification, GitRepo } from './types'

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'E-Commerce Platform',
    color: '#3b82f6',
    icon: 'ShoppingCart',
    description: 'Main web storefront and checkout pipeline managed by the web team.',
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'p2',
    name: 'Infrastructure Ops',
    color: '#10b981',
    icon: 'Server',
    description: 'Cloud infrastructure, DevOps pipelines, and platform reliability.',
    createdAt: '2024-01-20T09:00:00Z',
  },
  {
    id: 'p3',
    name: 'Client Portal',
    color: '#8b5cf6',
    icon: 'Users',
    description: 'B2B client-facing portal for enterprise customers.',
    createdAt: '2024-02-01T09:00:00Z',
  },
]

export const mockMessages: Record<string, Message[]> = {
  p1: [
    {
      id: 'm1',
      projectId: 'p1',
      source: 'jira',
      title: 'Bug: Payment gateway timeout on checkout',
      body: 'Users are experiencing payment gateway timeouts during checkout. The issue affects approximately 12% of transactions in the last 24 hours. Gateway response time exceeds 30 seconds.',
      from: 'johndoe@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      status: 'unread',
      priority: 'critical',
      labels: ['bug', 'payments', 'production'],
      externalLink: 'https://jira.example.com/browse/EC-1042',
    },
    {
      id: 'm2',
      projectId: 'p1',
      source: 'jira',
      title: 'Feature: Add Apple Pay support',
      body: 'As a mobile user, I want to pay with Apple Pay so I can checkout faster without entering card details manually. Design mockups attached.',
      from: 'pm@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      status: 'unread',
      priority: 'medium',
      labels: ['feature', 'payments', 'mobile'],
      externalLink: 'https://jira.example.com/browse/EC-1050',
    },
    {
      id: 'm3',
      projectId: 'p1',
      source: 'jira',
      title: 'Story: Mobile cart UX improvements',
      body: 'Improve the mobile shopping cart experience based on usability study findings. Key issues: hard to remove items, unclear total breakdown, missing coupon code field.',
      from: 'ux@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      status: 'read',
      priority: 'low',
      labels: ['ux', 'mobile', 'cart'],
    },
    {
      id: 'm4',
      projectId: 'p1',
      source: 'email',
      title: 'Client feedback on new checkout redesign',
      body: 'Hi team, we reviewed the new checkout redesign and overall it looks great! A few concerns: the button placement feels off on tablet, and the progress indicator is not visible enough.',
      from: 'sarah@clientco.com',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
      status: 'unread',
      priority: 'high',
      labels: ['client-feedback', 'checkout'],
    },
    {
      id: 'm5',
      projectId: 'p1',
      source: 'email',
      title: 'Weekly performance report ready',
      body: 'Your weekly performance report is ready. Key metrics: Conversion rate 3.2% (+0.4%), Average order value $87.50 (+$5), Cart abandonment 68% (-2%). Full report attached.',
      from: 'analytics@system.com',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
      status: 'read',
      priority: 'low',
      labels: ['analytics', 'weekly-report'],
    },
    {
      id: 'm6',
      projectId: 'p1',
      source: 'whatsapp',
      title: '🚨 URGENT: Production payment service is down!',
      body: 'Payment service returning 503 errors. Started 10 mins ago. Stripe dashboard shows no issues on their end. Could be our middleware. Investigating now.',
      from: 'Dev Team group',
      timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      status: 'unread',
      priority: 'critical',
      labels: ['incident', 'production', 'payments'],
    },
    {
      id: 'm7',
      projectId: 'p1',
      source: 'whatsapp',
      title: 'Can we push the release to Friday?',
      body: 'Hey, QA found 2 more issues in the release build. Nothing critical but would feel better shipping on Friday after another round. Thoughts?',
      from: 'PM group',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      status: 'unread',
      priority: 'medium',
      labels: ['release', 'planning'],
    },
  ],
  p2: [
    {
      id: 'm8',
      projectId: 'p2',
      source: 'jira',
      title: 'Incident P1: Memory leak in API server pod',
      body: 'prod-api-01 through prod-api-04 pods showing gradual memory increase. Started 6 hours ago. Current usage at 87% heap. No OOMKill yet but trending toward threshold.',
      from: 'oncall@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      status: 'unread',
      priority: 'critical',
      labels: ['incident', 'p1', 'api', 'memory'],
      externalLink: 'https://jira.example.com/browse/INF-892',
    },
    {
      id: 'm9',
      projectId: 'p2',
      source: 'jira',
      title: 'Task: Renew SSL certificates expiring in 7 days',
      body: 'SSL certs for api.example.com and checkout.example.com expire in 7 days. Need to renew via Let\'s Encrypt and update in AWS Certificate Manager before expiry.',
      from: 'devops@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      status: 'unread',
      priority: 'high',
      labels: ['ssl', 'security', 'deadline'],
      externalLink: 'https://jira.example.com/browse/INF-887',
    },
    {
      id: 'm10',
      projectId: 'p2',
      source: 'jira',
      title: 'Epic: Migrate MySQL to RDS Aurora',
      body: 'Plan and execute migration of primary MySQL 5.7 database to AWS RDS Aurora PostgreSQL. Estimated 3-sprint effort. Requires downtime window coordination with product team.',
      from: 'architect@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      status: 'read',
      priority: 'medium',
      labels: ['database', 'migration', 'epic'],
    },
    {
      id: 'm11',
      projectId: 'p2',
      source: 'email',
      title: 'AWS Budget Alert: 85% threshold exceeded',
      body: 'Your AWS account budget alert threshold of 85% has been exceeded. Current month spend: $4,250.00 of $5,000.00 budget. Primary drivers: EC2 (45%), RDS (30%), Data Transfer (15%).',
      from: 'aws-billing@amazon.com',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      status: 'unread',
      priority: 'high',
      labels: ['aws', 'billing', 'alert'],
    },
    {
      id: 'm12',
      projectId: 'p2',
      source: 'email',
      title: 'Security: OpenSSL patch CVE-2024-xxxx available',
      body: 'A critical OpenSSL vulnerability has been patched. CVE-2024-xxxx affects OpenSSL 3.0.x through 3.1.x. Patch available as 3.1.5. Recommend applying within 48 hours on all production systems.',
      from: 'security@alerts.com',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      status: 'unread',
      priority: 'high',
      labels: ['security', 'cve', 'patch'],
    },
    {
      id: 'm13',
      projectId: 'p2',
      source: 'whatsapp',
      title: 'CPU spike to 95% on prod-api-01',
      body: 'Seeing sustained CPU at 95% on prod-api-01. Load balancer is routing traffic but this node might need a restart. Checking for runaway processes now.',
      from: 'On-Call group',
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      status: 'unread',
      priority: 'critical',
      labels: ['cpu', 'production', 'incident'],
    },
    {
      id: 'm14',
      projectId: 'p2',
      source: 'whatsapp',
      title: 'Infra sync meeting moved to 3pm',
      body: 'Quick heads up — the weekly infra sync has been moved from 2pm to 3pm today due to PM conflict. Zoom link stays the same.',
      from: 'Team Chat',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      status: 'read',
      priority: 'low',
      labels: ['meeting'],
    },
  ],
  p3: [
    {
      id: 'm15',
      projectId: 'p3',
      source: 'jira',
      title: 'Bug: Dashboard loading fails for enterprise tier',
      body: 'Enterprise tier clients (>500 users) are experiencing dashboard load failures. The query timeout is set to 10 seconds but large datasets exceed this. Affecting ~15 enterprise accounts.',
      from: 'support@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      status: 'unread',
      priority: 'high',
      labels: ['bug', 'enterprise', 'dashboard'],
      externalLink: 'https://jira.example.com/browse/CP-234',
    },
    {
      id: 'm16',
      projectId: 'p3',
      source: 'jira',
      title: 'Feature: Export reports to Excel',
      body: 'Enterprise clients have requested the ability to export all dashboard reports to Excel/CSV format. This is a blocker for several Q2 renewals. High business value.',
      from: 'pm@jira',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      status: 'unread',
      priority: 'medium',
      labels: ['feature', 'export', 'enterprise'],
      externalLink: 'https://jira.example.com/browse/CP-240',
    },
    {
      id: 'm17',
      projectId: 'p3',
      source: 'email',
      title: 'Demo request for Q2 business review — ACME Corp',
      body: 'Hi, I\'m the CTO at ACME Corp. We\'re evaluating portal solutions for our Q2 business review and are very interested in your enterprise offering. Could we schedule a live demo this week?',
      from: 'cto@acmecorp.com',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString(),
      status: 'unread',
      priority: 'high',
      labels: ['demo', 'enterprise', 'lead'],
    },
    {
      id: 'm18',
      projectId: 'p3',
      source: 'email',
      title: 'Contract renewal reminder — 30 days',
      body: 'This is an automated reminder that the contract for Client XYZ (Enterprise tier, $48,000/yr) is due for renewal in 30 days. Account manager action required.',
      from: 'crm@system.internal',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
      status: 'read',
      priority: 'medium',
      labels: ['renewal', 'contract'],
    },
    {
      id: 'm19',
      projectId: 'p3',
      source: 'whatsapp',
      title: 'Logo looks different on portal vs brand guide',
      body: 'Hey, just noticed the logo in the portal header has different proportions compared to our brand guide PDF. The width seems stretched. Can someone look into this?',
      from: 'Client XYZ',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      status: 'read',
      priority: 'low',
      labels: ['branding', 'ui'],
    },
    {
      id: 'm20',
      projectId: 'p3',
      source: 'whatsapp',
      title: 'Any update on the status?',
      body: 'Following up on the dashboard loading issue we reported yesterday. Our team is blocked on end-of-month reporting. Is there an ETA for the fix?',
      from: 'PM group',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      status: 'unread',
      priority: 'medium',
      labels: ['follow-up', 'escalation'],
    },
  ],
}

export const mockTasks: Record<string, Task[]> = {
  p1: [
    {
      id: 't1',
      projectId: 'p1',
      title: 'Fix payment gateway timeout',
      description: 'Investigate and fix the 30-second timeout issue in the payment gateway middleware. Check Stripe API logs and our internal proxy configuration.',
      status: 'in-progress',
      priority: 'critical',
      type: 'jira',
      jiraKey: 'EC-1042',
      jiraLink: 'https://jira.example.com/browse/EC-1042',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      tags: ['payments', 'production', 'hotfix'],
    },
    {
      id: 't2',
      projectId: 'p1',
      title: 'Implement Apple Pay checkout',
      description: 'Integrate Apple Pay using the Stripe Payment Element. Requires HTTPS and domain verification file on checkout domain.',
      status: 'todo',
      priority: 'medium',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      tags: ['payments', 'mobile', 'feature'],
    },
    {
      id: 't3',
      projectId: 'p1',
      title: 'Write unit tests for cart service',
      description: 'Increase cart service test coverage to at least 80%. Focus on edge cases: empty cart, max items, discount code stacking.',
      status: 'todo',
      priority: 'low',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      tags: ['testing', 'cart'],
    },
    {
      id: 't4',
      projectId: 'p1',
      title: 'Deploy hotfix to production',
      description: 'Deploy the payment gateway timeout fix to production after QA sign-off.',
      status: 'done',
      priority: 'critical',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      tags: ['deployment', 'hotfix'],
    },
    {
      id: 't5',
      projectId: 'p1',
      title: 'Update product image CDN',
      description: 'Migrate product images from legacy S3 bucket to CloudFront CDN with WebP conversion.',
      status: 'done',
      priority: 'low',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
      tags: ['cdn', 'performance'],
    },
  ],
  p2: [
    {
      id: 't6',
      projectId: 'p2',
      title: 'Investigate memory leak in API pods',
      description: 'Profile memory usage in prod-api pods. Suspected cause: connection pool not releasing DB connections on timeout. Check datadog APM traces.',
      status: 'in-progress',
      priority: 'critical',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      tags: ['incident', 'memory', 'kubernetes'],
    },
    {
      id: 't7',
      projectId: 'p2',
      title: 'Renew SSL certificates',
      description: 'Renew SSL certs for api.example.com and checkout.example.com using certbot. Update in ACM and redeploy load balancer listeners.',
      status: 'todo',
      priority: 'high',
      dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      tags: ['ssl', 'security', 'deadline'],
    },
    {
      id: 't8',
      projectId: 'p2',
      title: 'Set up Grafana alerting rules',
      description: 'Configure Grafana alert rules for: CPU >80%, memory >85%, error rate >1%, P95 latency >500ms. Set up PagerDuty routing.',
      status: 'todo',
      priority: 'medium',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      tags: ['monitoring', 'grafana', 'alerting'],
    },
    {
      id: 't9',
      projectId: 'p2',
      title: 'Migrate auth service to k8s',
      description: 'Containerize the auth service and deploy to Kubernetes cluster. Requires secrets migration to k8s secrets, service mesh config, and ingress rules.',
      status: 'in-progress',
      priority: 'high',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
      tags: ['kubernetes', 'migration', 'auth'],
    },
    {
      id: 't10',
      projectId: 'p2',
      title: 'Document runbook for DB failover',
      description: 'Write step-by-step runbook for manual and automatic DB failover procedures. Include RTO/RPO expectations and rollback steps.',
      status: 'done',
      priority: 'medium',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
      tags: ['documentation', 'runbook', 'database'],
    },
  ],
  p3: [
    {
      id: 't11',
      projectId: 'p3',
      title: 'Fix enterprise dashboard loading',
      description: 'Increase query timeout for enterprise tier or implement pagination/lazy loading. Consider adding a dashboard_data_v2 endpoint with streaming.',
      status: 'in-progress',
      priority: 'high',
      type: 'jira',
      jiraKey: 'CP-234',
      jiraLink: 'https://jira.example.com/browse/CP-234',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      tags: ['bug', 'enterprise', 'performance'],
    },
    {
      id: 't12',
      projectId: 'p3',
      title: 'Build Excel export feature',
      description: 'Implement Excel export for all dashboard tables using ExcelJS library. Support custom date ranges and column selection.',
      status: 'todo',
      priority: 'medium',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      tags: ['feature', 'export', 'enterprise'],
    },
    {
      id: 't13',
      projectId: 'p3',
      title: 'Prepare Q2 demo environment',
      description: 'Set up isolated demo environment with ACME Corp branding, sample data, and all enterprise features enabled. Coordinate with sales team.',
      status: 'todo',
      priority: 'high',
      dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString(),
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
      tags: ['demo', 'sales', 'enterprise'],
    },
    {
      id: 't14',
      projectId: 'p3',
      title: 'Update branding assets',
      description: 'Replace legacy logo and color scheme with updated brand guide assets across all portal pages.',
      status: 'done',
      priority: 'low',
      type: 'local',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
      tags: ['branding', 'design'],
    },
  ],
}

export const mockQuickActions: Record<string, QuickAction[]> = {
  p1: [
    { id: 'qa1', projectId: 'p1', label: 'Jira Board', url: 'https://jira.example.com', icon: 'Trello', group: 'Dev', color: '#3b82f6', order: 0 },
    { id: 'qa2', projectId: 'p1', label: 'GitHub Repo', url: 'https://github.com', icon: 'Github', group: 'Dev', color: '#6b7280', order: 1 },
    { id: 'qa3', projectId: 'p1', label: 'Staging Site', url: 'https://staging.example.com', icon: 'Globe', group: 'Dev', color: '#f59e0b', order: 2 },
    { id: 'qa4', projectId: 'p1', label: 'Vercel Dashboard', url: 'https://vercel.com', icon: 'Triangle', group: 'Infra', color: '#1f2937', order: 3 },
    { id: 'qa5', projectId: 'p1', label: 'AWS Console', url: 'https://aws.amazon.com', icon: 'Cloud', group: 'Infra', color: '#f97316', order: 4 },
    { id: 'qa6', projectId: 'p1', label: 'Google Analytics', url: 'https://analytics.google.com', icon: 'BarChart2', group: 'Analytics', color: '#10b981', order: 5 },
    { id: 'qa7', projectId: 'p1', label: 'Mixpanel', url: 'https://mixpanel.com', icon: 'Activity', group: 'Analytics', color: '#8b5cf6', order: 6 },
  ],
  p2: [
    { id: 'qa8', projectId: 'p2', label: 'AWS Console', url: 'https://aws.amazon.com', icon: 'Cloud', group: 'Cloud', color: '#f97316', order: 0 },
    { id: 'qa9', projectId: 'p2', label: 'Terraform Cloud', url: 'https://app.terraform.io', icon: 'Box', group: 'Cloud', color: '#8b5cf6', order: 1 },
    { id: 'qa10', projectId: 'p2', label: 'Grafana', url: 'https://grafana.example.com', icon: 'Activity', group: 'Monitoring', color: '#f97316', order: 2 },
    { id: 'qa11', projectId: 'p2', label: 'PagerDuty', url: 'https://pagerduty.com', icon: 'Bell', group: 'Monitoring', color: '#10b981', order: 3 },
    { id: 'qa12', projectId: 'p2', label: 'Datadog', url: 'https://datadoghq.com', icon: 'BarChart', group: 'Monitoring', color: '#8b5cf6', order: 4 },
    { id: 'qa13', projectId: 'p2', label: 'ArgoCD', url: 'https://argocd.example.com', icon: 'GitBranch', group: 'DevOps', color: '#f97316', order: 5 },
    { id: 'qa14', projectId: 'p2', label: 'Harbor Registry', url: 'https://harbor.example.com', icon: 'Package', group: 'DevOps', color: '#3b82f6', order: 6 },
    { id: 'qa15', projectId: 'p2', label: 'K8s Dashboard', url: 'https://k8s.example.com', icon: 'Layers', group: 'DevOps', color: '#3b82f6', order: 7 },
  ],
  p3: [
    { id: 'qa16', projectId: 'p3', label: 'Jira Board', url: 'https://jira.example.com', icon: 'Trello', group: 'Dev', color: '#3b82f6', order: 0 },
    { id: 'qa17', projectId: 'p3', label: 'GitHub', url: 'https://github.com', icon: 'Github', group: 'Dev', color: '#6b7280', order: 1 },
    { id: 'qa18', projectId: 'p3', label: 'Staging', url: 'https://staging.portal.com', icon: 'Globe', group: 'Dev', color: '#f59e0b', order: 2 },
    { id: 'qa19', projectId: 'p3', label: 'Client Slack', url: 'https://slack.com', icon: 'MessageSquare', group: 'Client', color: '#8b5cf6', order: 3 },
    { id: 'qa20', projectId: 'p3', label: 'Support Desk', url: 'https://support.example.com', icon: 'LifeBuoy', group: 'Client', color: '#10b981', order: 4 },
    { id: 'qa21', projectId: 'p3', label: 'CRM', url: 'https://crm.example.com', icon: 'Users', group: 'Business', color: '#3b82f6', order: 5 },
    { id: 'qa22', projectId: 'p3', label: 'Analytics', url: 'https://analytics.example.com', icon: 'TrendingUp', group: 'Business', color: '#10b981', order: 6 },
  ],
}

export const mockIntegrations: Record<string, Integration[]> = {
  p1: [
    {
      id: 'int1',
      projectId: 'p1',
      type: 'jira',
      enabled: true,
      config: {
        serverUrl: 'https://jira.example.com',
        projectKey: 'EC',
        apiToken: 'jira_api_token_placeholder',
        username: 'admin@example.com',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    },
    {
      id: 'int2',
      projectId: 'p1',
      type: 'email',
      enabled: true,
      config: {
        provider: 'gmail',
        emailAddress: 'ecommerce@ops.dev',
        filterLabel: 'ecommerce-platform',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
    {
      id: 'int3',
      projectId: 'p1',
      type: 'whatsapp',
      enabled: true,
      config: {
        apiToken: 'wa_api_token_placeholder',
        groupIds: 'dev-team-123,pm-group-456',
        webhookUrl: 'https://ops.dev/webhooks/whatsapp/p1',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    },
    {
      id: 'int-gl1',
      projectId: 'p1',
      type: 'gitlab',
      enabled: false,
      config: { instanceUrl: '', projectPath: '', token: '' },
    },
  ],
  p2: [
    {
      id: 'int4',
      projectId: 'p2',
      type: 'jira',
      enabled: true,
      config: {
        serverUrl: 'https://jira.example.com',
        projectKey: 'INF',
        apiToken: 'jira_api_token_placeholder',
        username: 'devops@example.com',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
    {
      id: 'int5',
      projectId: 'p2',
      type: 'email',
      enabled: true,
      config: {
        provider: 'gmail',
        emailAddress: 'infra@ops.dev',
        filterLabel: 'infrastructure',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
    {
      id: 'int6',
      projectId: 'p2',
      type: 'whatsapp',
      enabled: true,
      config: {
        apiToken: 'wa_api_token_placeholder',
        groupIds: 'oncall-group-789,infra-team-012',
        webhookUrl: 'https://ops.dev/webhooks/whatsapp/p2',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    },
    {
      id: 'int-gl2',
      projectId: 'p2',
      type: 'gitlab',
      enabled: false,
      config: { instanceUrl: '', projectPath: '', token: '' },
    },
  ],
  p3: [
    {
      id: 'int7',
      projectId: 'p3',
      type: 'jira',
      enabled: true,
      config: {
        serverUrl: 'https://jira.example.com',
        projectKey: 'CP',
        apiToken: 'jira_api_token_placeholder',
        username: 'portal@example.com',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    },
    {
      id: 'int8',
      projectId: 'p3',
      type: 'email',
      enabled: true,
      config: {
        provider: 'outlook',
        emailAddress: 'portal@ops.dev',
        filterLabel: 'client-portal',
      },
      lastSync: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    },
    {
      id: 'int9',
      projectId: 'p3',
      type: 'whatsapp',
      enabled: false,
      config: {
        apiToken: '',
        groupIds: '',
        webhookUrl: '',
      },
    },
    {
      id: 'int-gl3',
      projectId: 'p3',
      type: 'gitlab',
      enabled: false,
      config: { instanceUrl: '', projectPath: '', token: '' },
    },
  ],
}

export const mockNotifications: AppNotification[] = []

// ─── Mock Git Repositories ────────────────────────────────────────────────────

const m = (minAgo: number) => new Date(Date.now() - minAgo * 60 * 1000).toISOString()

export const mockRepos: Record<string, GitRepo[]> = {
  // ── E-Commerce Platform ────────────────────────────────────────────────────
  p1: [
    {
      id: 'r1',
      projectId: 'p1',
      provider: 'github',
      name: 'company/ecommerce-frontend',
      displayName: 'E-Commerce Frontend',
      url: 'https://github.com/company/ecommerce-frontend',
      defaultBranch: 'main',
      description: 'Next.js storefront — product catalog, cart, and checkout UI',
      lastSync: m(3),
      openPRs: 2,
      openIssues: 5,
      pipelineStatus: 'success',
      stars: 24,
      events: [
        {
          id: 're1-1',
          repoId: 'r1',
          type: 'push',
          title: 'fix: handle payment gateway timeout gracefully',
          author: 'john.doe',
          timestamp: m(2),
          url: 'https://github.com/company/ecommerce-frontend/commit/a3f9c1d',
          branch: 'main',
          sha: 'a3f9c1d',
        },
        {
          id: 're1-2',
          repoId: 'r1',
          type: 'pull_request',
          title: 'feat: Add Apple Pay to checkout flow',
          author: 'sarah.smith',
          timestamp: m(18),
          url: 'https://github.com/company/ecommerce-frontend/pull/142',
          status: 'open',
          number: 142,
          branch: 'feature/apple-pay',
        },
        {
          id: 're1-3',
          repoId: 'r1',
          type: 'pipeline',
          title: 'CI #89 — Build & Deploy to staging',
          author: 'github-actions',
          timestamp: m(25),
          url: 'https://github.com/company/ecommerce-frontend/actions/runs/89',
          status: 'success',
          branch: 'main',
        },
        {
          id: 're1-4',
          repoId: 'r1',
          type: 'pull_request',
          title: 'refactor: Improve mobile cart UX',
          author: 'alex.jones',
          timestamp: m(180),
          url: 'https://github.com/company/ecommerce-frontend/pull/141',
          status: 'merged',
          number: 141,
          branch: 'refactor/mobile-cart',
        },
        {
          id: 're1-5',
          repoId: 'r1',
          type: 'push',
          title: 'chore: update product image CDN endpoint',
          author: 'alex.jones',
          timestamp: m(240),
          url: 'https://github.com/company/ecommerce-frontend/commit/b12e4fa',
          branch: 'main',
          sha: 'b12e4fa',
        },
      ],
    },
    {
      id: 'r2',
      projectId: 'p1',
      provider: 'github',
      name: 'company/ecommerce-api',
      displayName: 'E-Commerce API',
      url: 'https://github.com/company/ecommerce-api',
      defaultBranch: 'main',
      description: 'Node.js REST API — orders, inventory, payments, and auth',
      lastSync: m(5),
      openPRs: 3,
      openIssues: 12,
      pipelineStatus: 'failed',
      stars: 18,
      events: [
        {
          id: 're2-1',
          repoId: 'r2',
          type: 'pipeline',
          title: 'CI #104 — Unit tests & coverage check',
          author: 'github-actions',
          timestamp: m(8),
          url: 'https://github.com/company/ecommerce-api/actions/runs/104',
          status: 'failed',
          branch: 'main',
        },
        {
          id: 're2-2',
          repoId: 'r2',
          type: 'pull_request',
          title: 'fix: Payment service timeout — increase Stripe timeout to 30s',
          author: 'john.doe',
          timestamp: m(45),
          url: 'https://github.com/company/ecommerce-api/pull/89',
          status: 'open',
          number: 89,
          branch: 'fix/payment-timeout',
        },
        {
          id: 're2-3',
          repoId: 'r2',
          type: 'push',
          title: 'wip: investigating heap allocation in order service',
          author: 'sarah.smith',
          timestamp: m(90),
          url: 'https://github.com/company/ecommerce-api/commit/c9a1e32',
          branch: 'fix/payment-timeout',
          sha: 'c9a1e32',
        },
        {
          id: 're2-4',
          repoId: 'r2',
          type: 'issue',
          title: 'Memory leak in order-processing worker',
          author: 'john.doe',
          timestamp: m(150),
          url: 'https://github.com/company/ecommerce-api/issues/210',
          status: 'open',
          number: 210,
        },
        {
          id: 're2-5',
          repoId: 'r2',
          type: 'pull_request',
          title: 'chore: Bump express from 4.18.1 to 4.19.2',
          author: 'dependabot',
          timestamp: m(300),
          url: 'https://github.com/company/ecommerce-api/pull/88',
          status: 'open',
          number: 88,
          branch: 'deps/express-4.19.2',
        },
      ],
    },
  ],

  // ── Infrastructure Ops ────────────────────────────────────────────────────
  p2: [
    {
      id: 'r3',
      projectId: 'p2',
      provider: 'gitlab',
      name: 'infra/terraform-modules',
      displayName: 'Terraform Modules',
      url: 'https://gitlab.company.com/infra/terraform-modules',
      apiUrl: 'https://gitlab.company.com',
      defaultBranch: 'main',
      description: 'Shared Terraform modules for AWS infrastructure',
      lastSync: m(7),
      openPRs: 1,
      openIssues: 3,
      pipelineStatus: 'running',
      events: [
        {
          id: 're3-1',
          repoId: 'r3',
          type: 'pipeline',
          title: 'Pipeline #312 — terraform plan & validate',
          author: 'gitlab-ci',
          timestamp: m(1),
          url: 'https://gitlab.company.com/infra/terraform-modules/-/pipelines/312',
          status: 'running',
          branch: 'main',
        },
        {
          id: 're3-2',
          repoId: 'r3',
          type: 'merge_request',
          title: 'feat: Add RDS Aurora module with multi-AZ support',
          author: 'devops.lead',
          timestamp: m(30),
          url: 'https://gitlab.company.com/infra/terraform-modules/-/merge_requests/45',
          status: 'open',
          number: 45,
          branch: 'feat/rds-aurora-module',
        },
        {
          id: 're3-3',
          repoId: 'r3',
          type: 'push',
          title: 'fix: EKS node group launch template permissions',
          author: 'devops.lead',
          timestamp: m(60),
          url: 'https://gitlab.company.com/infra/terraform-modules/-/commit/d4b2f8a',
          branch: 'main',
          sha: 'd4b2f8a',
        },
        {
          id: 're3-4',
          repoId: 'r3',
          type: 'pipeline',
          title: 'Pipeline #311 — terraform plan & validate',
          author: 'gitlab-ci',
          timestamp: m(65),
          url: 'https://gitlab.company.com/infra/terraform-modules/-/pipelines/311',
          status: 'success',
          branch: 'main',
        },
        {
          id: 're3-5',
          repoId: 'r3',
          type: 'push',
          title: 'chore: Bump AWS provider to 5.39.0',
          author: 'ops.bot',
          timestamp: m(480),
          url: 'https://gitlab.company.com/infra/terraform-modules/-/commit/e5c3a9b',
          branch: 'main',
          sha: 'e5c3a9b',
        },
      ],
    },
    {
      id: 'r4',
      projectId: 'p2',
      provider: 'github',
      name: 'company/k8s-manifests',
      displayName: 'K8s Manifests',
      url: 'https://github.com/company/k8s-manifests',
      defaultBranch: 'main',
      description: 'Kubernetes deployment manifests and Helm charts',
      lastSync: m(10),
      openPRs: 0,
      openIssues: 2,
      pipelineStatus: 'success',
      events: [
        {
          id: 're4-1',
          repoId: 'r4',
          type: 'push',
          title: 'fix: increase api-server memory limit to 2Gi',
          author: 'devops.lead',
          timestamp: m(15),
          url: 'https://github.com/company/k8s-manifests/commit/f6d1c3e',
          branch: 'main',
          sha: 'f6d1c3e',
        },
        {
          id: 're4-2',
          repoId: 'r4',
          type: 'pipeline',
          title: 'CI #67 — Lint & dry-run apply',
          author: 'github-actions',
          timestamp: m(16),
          url: 'https://github.com/company/k8s-manifests/actions/runs/67',
          status: 'success',
          branch: 'main',
        },
        {
          id: 're4-3',
          repoId: 'r4',
          type: 'push',
          title: 'feat: add HPA for worker deployment',
          author: 'sre.engineer',
          timestamp: m(120),
          url: 'https://github.com/company/k8s-manifests/commit/a7c4e2d',
          branch: 'main',
          sha: 'a7c4e2d',
        },
        {
          id: 're4-4',
          repoId: 'r4',
          type: 'push',
          title: 'chore: rotate cert-manager service account secret',
          author: 'devops.lead',
          timestamp: m(360),
          url: 'https://github.com/company/k8s-manifests/commit/b8f5d1a',
          branch: 'main',
          sha: 'b8f5d1a',
        },
      ],
    },
  ],

  // ── Client Portal ────────────────────────────────────────────────────────
  p3: [
    {
      id: 'r5',
      projectId: 'p3',
      provider: 'github',
      name: 'company/portal-frontend',
      displayName: 'Portal Frontend',
      url: 'https://github.com/company/portal-frontend',
      defaultBranch: 'main',
      description: 'React dashboard for B2B enterprise clients',
      lastSync: m(4),
      openPRs: 3,
      openIssues: 8,
      pipelineStatus: 'success',
      stars: 9,
      events: [
        {
          id: 're5-1',
          repoId: 'r5',
          type: 'pull_request',
          title: 'fix: Dashboard fails to load for enterprise tier accounts',
          author: 'dev.frontend',
          timestamp: m(20),
          url: 'https://github.com/company/portal-frontend/pull/78',
          status: 'open',
          number: 78,
          branch: 'fix/enterprise-dashboard',
        },
        {
          id: 're5-2',
          repoId: 'r5',
          type: 'pipeline',
          title: 'CI #201 — Build, test & deploy staging',
          author: 'github-actions',
          timestamp: m(22),
          url: 'https://github.com/company/portal-frontend/actions/runs/201',
          status: 'success',
          branch: 'fix/enterprise-dashboard',
        },
        {
          id: 're5-3',
          repoId: 'r5',
          type: 'pull_request',
          title: 'feat: Excel export for analytics reports',
          author: 'dev.fullstack',
          timestamp: m(90),
          url: 'https://github.com/company/portal-frontend/pull/77',
          status: 'open',
          number: 77,
          branch: 'feat/excel-export',
        },
        {
          id: 're5-4',
          repoId: 'r5',
          type: 'push',
          title: 'chore: Update company logo and brand colors',
          author: 'dev.frontend',
          timestamp: m(200),
          url: 'https://github.com/company/portal-frontend/commit/c1a9e7f',
          branch: 'main',
          sha: 'c1a9e7f',
        },
        {
          id: 're5-5',
          repoId: 'r5',
          type: 'release',
          title: 'Release v2.4.1 — Bug fixes & performance',
          author: 'dev.lead',
          timestamp: m(1440),
          url: 'https://github.com/company/portal-frontend/releases/tag/v2.4.1',
          status: 'closed',
        },
      ],
    },
    {
      id: 'r6',
      projectId: 'p3',
      provider: 'gitlab',
      name: 'clients/portal-api',
      displayName: 'Portal API',
      url: 'https://gitlab.company.com/clients/portal-api',
      apiUrl: 'https://gitlab.company.com',
      defaultBranch: 'develop',
      description: 'Django REST API — client data, reports, and permissions',
      lastSync: m(12),
      openPRs: 2,
      openIssues: 6,
      pipelineStatus: 'failed',
      events: [
        {
          id: 're6-1',
          repoId: 'r6',
          type: 'pipeline',
          title: 'Pipeline #188 — test & coverage',
          author: 'gitlab-ci',
          timestamp: m(14),
          url: 'https://gitlab.company.com/clients/portal-api/-/pipelines/188',
          status: 'failed',
          branch: 'develop',
        },
        {
          id: 're6-2',
          repoId: 'r6',
          type: 'merge_request',
          title: 'fix: Enterprise dashboard query N+1 problem',
          author: 'dev.backend',
          timestamp: m(50),
          url: 'https://gitlab.company.com/clients/portal-api/-/merge_requests/33',
          status: 'open',
          number: 33,
          branch: 'fix/enterprise-n-plus-1',
        },
        {
          id: 're6-3',
          repoId: 'r6',
          type: 'push',
          title: 'fix: add missing db index on reports.client_id',
          author: 'dev.backend',
          timestamp: m(55),
          url: 'https://gitlab.company.com/clients/portal-api/-/commit/e9b2c4a',
          branch: 'fix/enterprise-n-plus-1',
          sha: 'e9b2c4a',
        },
        {
          id: 're6-4',
          repoId: 'r6',
          type: 'merge_request',
          title: 'feat: Excel export endpoint — /api/reports/export',
          author: 'dev.fullstack',
          timestamp: m(180),
          url: 'https://gitlab.company.com/clients/portal-api/-/merge_requests/32',
          status: 'open',
          number: 32,
          branch: 'feat/excel-export-api',
        },
      ],
    },
  ],
}
